version: "3"

services:
  oracle-test:
    build:
      context: docker/oracle
    volumes:
      - .:/lapin
      - /lapin/build
      - /lapin/node_modules
    networks:
      - lapin

networks:
  lapin:
