version: "3"
services:
  # mysql
  mysql:
    image: "mysql:5.7.37"
    container_name: "lapin-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # mariadb
  mariadb:
    image: "mariadb:10.8.4"
    container_name: "lapin-mariadb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # postgres
  postgres:
    # mdillon/postgis is postgres + PostGIS (only). if you need additional
    # extensions, it's probably time to create a purpose-built image with all
    # necessary extensions. sorry, and thanks for adding support for them!
    image: "postgis/postgis:14-3.3"
    container_name: "lapin-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  postgres-12:
    # mdillon/postgis is postgres + PostGIS (only). if you need additional
    # extensions, it's probably time to create a purpose-built image with all
    # necessary extensions. sorry, and thanks for adding support for them!
    image: "postgis/postgis:12-2.5"
    container_name: "lapin-postgres-12"
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    container_name: "lapin-mssql"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin12345"
      ACCEPT_EULA: "Y"

  # cockroachdb
  cockroachdb:
    image: "cockroachdb/cockroach:v22.1.6"
    container_name: "lapin-cockroachdb"
    command: start-single-node --insecure --cache=.25 --store=type=mem,size=.25
    ports:
      - "26257:26257"

  oracle:
    image: imnotjames/oracle-xe:18
    container_name: "lapin-oracle"
    ports:
      - "1521:1521"
    networks:
      - default
      - lapin

  # google cloud spanner
  spanner:
    image: alexmesser/spanner-emulator
    container_name: "lapin-spanner"
    ports:
      - "9010:9010"
      - "9020:9020"

  # mongodb
  mongodb:
    image: "mongo:5.0.12"
    container_name: "lapin-mongodb"
    ports:
      - "27017:27017"
  # redis
  # redis:
  #   image: "redis:3.0.3"
  #   container_name: "lapin-redis"
  #   ports:
  #     - "6379:6379"

#volumes:
#  volume-hana-xe:
#  mysql8_volume:

networks:
  lapin:
