contact_links:
  - name: 🤔 Questions, General Support, and Help
    url: https://github.com/lapin/lapin/blob/master/docs/support.md
    about: This issue tracker is not for support questions. Please refer to the lapin community support documentation.
