name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
jobs:
  check-lint:
    name: Check fmt with Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Check Lint
        run: yarn lint

  check-test:
    name: Check Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Test Program
        run: yarn test
